Unify writing of .dev/.current for libraries from a VCS
Fixes inconsistent use of .dev and .current that caused updates to
fail when subDir is not null.

    > haxelib newrepo
    Local repository created (/tmp/foobar/.haxelib)

    > haxelib --never git yaml https://github.com/mikestead/hx-yaml master src
    Installing yaml from https://github.com/mikestead/hx-yaml branch: master
    Development directory set to /tmp/foobar/.haxelib/yaml/git/src

    > haxelib --never git yaml https://github.com/mikestead/hx-yaml master src
    You already have yaml version git installed.
    Updating yaml version git ...
    Error: [file_contents,/tmp/foobar/.haxelib/yaml/.current]

    Called from /home/jonas/Code/haxe/std/neko/_std/sys/io/File.hx line 30
    Called from haxelib/client/Main.hx line 1307
    Called from haxelib/client/Main.hx line 1476
    Called from a C function
    Called from haxelib/client/Main.hx line 1446
    Called from haxelib/client/Main.hx line 188
    Called from haxelib/client/Main.hx line 422